//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reation
    {
        public System.Guid Id { get; set; }
        public Nullable<bool> Like { get; set; }
        public System.DateTime CreationData { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid PostId { get; set; }
        public string UserIP { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
